[package]
name = "gi"
version = "0.1.0"
authors = ["Makris Spiros <makris.spiros@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.2.8"
shipyard = "0.4.1"

bracket-random = "0.7.0"