[package]
name = "gi"
version = "0.1.0"
authors = ["Makris Spiros <makris.spiros@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
